export const INDEX_BRANDS = 'INDEX_BRANDS';
export const INDEX_BRANDS_SUCCESS = 'INDEX_BRANDS_SUCCESS';
export const INDEX_BRANDS_FAIL = 'INDEX_BRANDS_FAIL';

export const CREATE_ONE_BRAND = 'CREATE_ONE_BRAND';
export const CREATE_ONE_BRAND_SUCCESS = 'CREATE_ONE_BRAND_SUCCESS';
export const CREATE_ONE_BRAND_FAIL = 'CREATE_ONE_BRAND_FAIL';

export const UPDATE_ONE_BRAND = 'UPDATE_ONE_BRAND';
export const UPDATE_ONE_BRAND_SUCCESS = 'UPDATE_ONE_BRAND_SUCCESS';
export const UPDATE_ONE_BRAND_FAIL = 'UPDATE_ONE_BRAND_FAIL';

export const DELETE_ONE_BRAND = 'DELETE_ONE_BRAND';
export const DELETE_ONE_BRAND_SUCCESS = 'DELETE_ONE_BRAND_SUCCESS';
export const DELETE_ONE_BRAND_FAIL = 'DELETE_ONE_BRAND_FAIL';

export const INDEX_MANUFACTURERS = 'INDEX_MANUFACTURERS';
export const INDEX_MANUFACTURERS_SUCCESS = 'INDEX_MANUFACTURERS_SUCCESS';
export const INDEX_MANUFACTURERS_FAIL = 'INDEX_MANUFACTURERS_FAIL';

export const CREATE_ONE_MANUFACTURER = 'CREATE_ONE_MANUFACTURER';
export const CREATE_ONE_MANUFACTURER_SUCCESS = 'CREATE_ONE_MANUFACTURER_SUCCESS';
export const CREATE_ONE_MANUFACTURER_FAIL = 'CREATE_ONE_MANUFACTURER_FAIL';

export const UPDATE_ONE_MANUFACTURER = 'UPDATE_ONE_MANUFACTURER';
export const UPDATE_ONE_MANUFACTURER_SUCCESS = 'UPDATE_ONE_MANUFACTURER_SUCCESS';
export const UPDATE_ONE_MANUFACTURER_FAIL = 'UPDATE_ONE_MANUFACTURER_FAIL';

export const DELETE_ONE_MANUFACTURER = 'DELETE_ONE_MANUFACTURER';
export const DELETE_ONE_MANUFACTURER_SUCCESS = 'DELETE_ONE_MANUFACTURER_SUCCESS';
export const DELETE_ONE_MANUFACTURER_FAIL = 'DELETE_ONE_MANUFACTURER_FAIL';

export const INDEX_COMPANIES = 'INDEX_COMPANIES';
export const INDEX_COMPANIES_SUCCESS = 'INDEX_COMPANIES_SUCCESS';
export const INDEX_COMPANIES_FAIL = 'INDEX_COMPANIES_FAIL';

export const CREATE_ONE_COMPANY = 'CREATE_ONE_COMPANY';
export const CREATE_ONE_COMPANY_SUCCESS = 'CREATE_ONE_COMPANY_SUCCESS';
export const CREATE_ONE_COMPANY_FAIL = 'CREATE_ONE_COMPANY_FAIL';

export const UPDATE_ONE_COMPANY = 'UPDATE_ONE_COMPANY';
export const UPDATE_ONE_COMPANY_SUCCESS = 'UPDATE_ONE_COMPANY_SUCCESS';
export const UPDATE_ONE_COMPANY_FAIL = 'UPDATE_ONE_COMPANY_FAIL';

export const DELETE_ONE_COMPANY = 'DELETE_ONE_COMPANY';
export const DELETE_ONE_COMPANY_SUCCESS = 'DELETE_ONE_COMPANY_SUCCESS';
export const DELETE_ONE_COMPANY_FAIL = 'DELETE_ONE_COMPANY_FAIL';

export const INDEX_USERS = 'INDEX_USERS';
export const INDEX_USERS_SUCCESS = 'INDEX_USERS_SUCCESS';
export const INDEX_USERS_FAIL = 'INDEX_USERS_FAIL';

export const CREATE_ONE_USER = 'CREATE_ONE_USER';
export const CREATE_ONE_USER_SUCCESS = 'CREATE_ONE_USER_SUCCESS';
export const CREATE_ONE_USER_FAIL = 'CREATE_ONE_USER_FAIL';

export const UPDATE_ONE_USER = 'UPDATE_ONE_USER';
export const UPDATE_ONE_USER_SUCCESS = 'UPDATE_ONE_USER_SUCCESS';
export const UPDATE_ONE_USER_FAIL = 'UPDATE_ONE_USER_FAIL';

export const DELETE_ONE_USER = 'DELETE_ONE_USER';
export const DELETE_ONE_USER_SUCCESS = 'DELETE_ONE_USER_SUCCESS';
export const DELETE_ONE_USER_FAIL = 'DELETE_ONE_USER_FAIL';

export const INDEX_BRANCHES = 'INDEX_BRANCHES';
export const INDEX_BRANCHES_SUCCESS = 'INDEX_BRANCHES_SUCCESS';
export const INDEX_BRANCHES_FAIL = 'INDEX_BRANCHES_FAIL';

export const CREATE_ONE_BRANCH = 'CREATE_ONE_BRANCH';
export const CREATE_ONE_BRANCH_SUCCESS = 'CREATE_ONE_BRANCH_SUCCESS';
export const CREATE_ONE_BRANCH_FAIL = 'CREATE_ONE_BRANCH_FAIL';

export const UPDATE_ONE_BRANCH = 'UPDATE_ONE_BRANCH';
export const UPDATE_ONE_BRANCH_SUCCESS = 'UPDATE_ONE_BRANCH_SUCCESS';
export const UPDATE_ONE_BRANCH_FAIL = 'UPDATE_ONE_BRANCH_FAIL';

export const DELETE_ONE_BRANCH = 'DELETE_ONE_BRANCH';
export const DELETE_ONE_BRANCH_SUCCESS = 'DELETE_ONE_BRANCH_SUCCESS';
export const DELETE_ONE_BRANCH_FAIL = 'DELETE_ONE_BRANCH_FAIL';

export const INDEX_BUSINESS_CATEGORIES = 'INDEX_BUSINESS_CATEGORIES';
export const INDEX_BUSINESS_CATEGORIES_SUCCESS = 'INDEX_BUSINESS_CATEGORIES_SUCCESS';
export const INDEX_BUSINESS_CATEGORIES_FAIL = 'INDEX_BUSINESS_CATEGORIES_FAIL';

export const CREATE_ONE_BUSINESS_CATEGORY = 'CREATE_ONE_BUSINESS_CATEGORY';
export const CREATE_ONE_BUSINESS_CATEGORY_SUCCESS = 'CREATE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const CREATE_ONE_BUSINESS_CATEGORY_FAIL = 'CREATE_ONE_BUSINESS_CATEGORY_FAIL';

export const UPDATE_ONE_BUSINESS_CATEGORY = 'UPDATE_ONE_BUSINESS_CATEGORY';
export const UPDATE_ONE_BUSINESS_CATEGORY_SUCCESS = 'UPDATE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const UPDATE_ONE_BUSINESS_CATEGORY_FAIL = 'UPDATE_ONE_BUSINESS_CATEGORY_FAIL';

export const DELETE_ONE_BUSINESS_CATEGORY = 'DELETE_ONE_BUSINESS_CATEGORY';
export const DELETE_ONE_BUSINESS_CATEGORY_SUCCESS = 'DELETE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const DELETE_ONE_BUSINESS_CATEGORY_FAIL = 'DELETE_ONE_BUSINESS_CATEGORY_FAIL';

export const INDEX_PRODUCT_CATEGORIES = 'INDEX_PRODUCT_CATEGORIES';
export const INDEX_PRODUCT_CATEGORIES_SUCCESS = 'INDEX_PRODUCT_CATEGORIES_SUCCESS';
export const INDEX_PRODUCT_CATEGORIES_FAIL = 'INDEX_PRODUCT_CATEGORIES_FAIL';

export const CREATE_ONE_PRODUCT_CATEGORY = 'CREATE_ONE_PRODUCT_CATEGORY';
export const CREATE_ONE_PRODUCT_CATEGORY_SUCCESS = 'CREATE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const CREATE_ONE_PRODUCT_CATEGORY_FAIL = 'CREATE_ONE_PRODUCT_CATEGORY_FAIL';

export const UPDATE_ONE_PRODUCT_CATEGORY = 'UPDATE_ONE_PRODUCT_CATEGORY';
export const UPDATE_ONE_PRODUCT_CATEGORY_SUCCESS = 'UPDATE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_ONE_PRODUCT_CATEGORY_FAIL = 'UPDATE_ONE_PRODUCT_CATEGORY_FAIL';

export const DELETE_ONE_PRODUCT_CATEGORY = 'DELETE_ONE_PRODUCT_CATEGORY';
export const DELETE_ONE_PRODUCT_CATEGORY_SUCCESS = 'DELETE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_ONE_PRODUCT_CATEGORY_FAIL = 'DELETE_ONE_PRODUCT_CATEGORY_FAIL';

export const INDEX_PRODUCTS = 'INDEX_PRODUCTS';
export const INDEX_PRODUCTS_SUCCESS = 'INDEX_PRODUCTS_SUCCESS';
export const INDEX_PRODUCTS_FAIL = 'INDEX_PRODUCTS_FAIL';

export const CREATE_ONE_PRODUCT = 'CREATE_ONE_PRODUCT';
export const CREATE_ONE_PRODUCT_SUCCESS = 'CREATE_ONE_PRODUCT_SUCCESS';
export const CREATE_ONE_PRODUCT_FAIL = 'CREATE_ONE_PRODUCT_FAIL';

export const UPDATE_ONE_PRODUCT = 'UPDATE_ONE_PRODUCT';
export const UPDATE_ONE_PRODUCT_SUCCESS = 'UPDATE_ONE_PRODUCT_SUCCESS';
export const UPDATE_ONE_PRODUCT_FAIL = 'UPDATE_ONE_PRODUCT_FAIL';

export const DELETE_ONE_PRODUCT = 'DELETE_ONE_PRODUCT';
export const DELETE_ONE_PRODUCT_SUCCESS = 'DELETE_ONE_PRODUCT_SUCCESS';
export const DELETE_ONE_PRODUCT_FAIL = 'DELETE_ONE_PRODUCT_FAIL';

export const INDEX_PRODUCT_SEGMENTS = 'INDEX_PRODUCT_SEGMENTS';
export const INDEX_PRODUCT_SEGMENTS_SUCCESS = 'INDEX_PRODUCT_SEGMENTS_SUCCESS';
export const INDEX_PRODUCT_SEGMENTS_FAIL = 'INDEX_PRODUCT_SEGMENTS_FAIL';

export const CREATE_ONE_PRODUCT_SEGMENT = 'CREATE_ONE_PRODUCT_SEGMENT';
export const CREATE_ONE_PRODUCT_SEGMENT_SUCCESS = 'CREATE_ONE_PRODUCT_SEGMENT_SUCCESS';
export const CREATE_ONE_PRODUCT_SEGMENT_FAIL = 'CREATE_ONE_PRODUCT_SEGMENT_FAIL';

export const UPDATE_ONE_PRODUCT_SEGMENT  = 'UPDATE_ONE_PRODUCT_SEGMENT';
export const UPDATE_ONE_PRODUCT_SEGMENT_SUCCESS = 'UPDATE_ONE_PRODUCT_SEGMENT_SUCCESS';
export const UPDATE_ONE_PRODUCT_SEGMENT_FAIL = 'UPDATE_ONE_PRODUCT_SEGMENT_FAIL';

export const DELETE_ONE_PRODUCT_SEGMENT = 'DELETE_ONE_PRODUCT_SEGMENT';
export const DELETE_ONE_PRODUCT_SEGMENT_SUCCESS = 'DELETE_ONE_PRODUCT_SEGMENT_SUCCESS';
export const DELETE_ONE_PRODUCT_SEGMENT_FAIL = 'DELETE_ONE_PRODUCT_SEGMENT_FAIL';


export const INDEX_PRODUCT_SEGMENT_ENTRIES = 'INDEX_PRODUCT_SEGMENT_ENTRIES';
export const INDEX_PRODUCT_SEGMENT_ENTRIES_SUCCESS = 'INDEX_PRODUCT_SEGMENT_ENTRIES_SUCCESS';
export const INDEX_PRODUCT_SEGMENT_ENTRIES_FAIL = 'INDEX_PRODUCT_SEGMENT_ENTRIES_FAIL';

export const CREATE_ONE_PRODUCT_SEGMENT_ENTRY = 'CREATE_ONE_PRODUCT_SEGMENT_ENTRY';
export const CREATE_ONE_PRODUCT_SEGMENT_ENTRY_SUCCESS = 'CREATE_ONE_PRODUCT_SEGMENT_ENTRY_SUCCESS';
export const CREATE_ONE_PRODUCT_SEGMENT_ENTRY_FAIL = 'CREATE_ONE_PRODUCT_SEGMENT_ENTRY_FAIL';

export const UPDATE_ONE_PRODUCT_SEGMENT_ENTRY   = 'UPDATE_ONE_PRODUCT_SEGMENT_ENTRY';
export const UPDATE_ONE_PRODUCT_SEGMENT_ENTRY_SUCCESS = 'UPDATE_ONE_PRODUCT_SEGMENT_ENTRY_SUCCESS';
export const UPDATE_ONE_PRODUCT_SEGMENT_ENTRY_FAIL = 'UPDATE_ONE_PRODUCT_SEGMENT_ENTRY_FAIL';

export const DELETE_ONE_PRODUCT_SEGMENT_ENTRY = 'DELETE_ONE_PRODUCT_SEGMENT_ENTRY';
export const DELETE_ONE_PRODUCT_SEGMENT_ENTRY_SUCCESS = 'DELETE_ONE_PRODUCT_SEGMENT_ENTRY_SUCCESS';
export const DELETE_ONE_PRODUCT_SEGMENT_ENTRY_FAIL = 'DELETE_ONE_PRODUCT_SEGMENT_ENTRY_FAIL';

export const INDEX_CUSTOMERS = 'INDEX_CUSTOMERS';
export const INDEX_CUSTOMERS_SUCCESS = 'INDEX_CUSTOMERS_SUCCESS';
export const INDEX_CUSTOMERS_FAIL = 'INDEX_CUSTOMERS_FAIL';

export const CREATE_ONE_CUSTOMER = 'CREATE_ONE_CUSTOMER';
export const CREATE_ONE_CUSTOMER_SUCCESS = 'CREATE_ONE_CUSTOMER_SUCCESS';
export const CREATE_ONE_CUSTOMER_FAIL = 'CREATE_ONE_CUSTOMER_FAIL';

export const UPDATE_ONE_CUSTOMER = 'UPDATE_ONE_CUSTOMER';
export const UPDATE_ONE_CUSTOMER_SUCCESS = 'UPDATE_ONE_CUSTOMER_SUCCESS';
export const UPDATE_ONE_CUSTOMER_FAIL = 'UPDATE_ONE_CUSTOMER_FAIL';

export const DELETE_ONE_CUSTOMER = 'DELETE_ONE_CUSTOMER';
export const DELETE_ONE_CUSTOMER_SUCCESS = 'DELETE_ONE_CUSTOMER_SUCCESS';
export const DELETE_ONE_CUSTOMER_FAIL = 'DELETE_ONE_CUSTOMER_FAIL';

export const INDEX_MEASUREMENT_UNITS = 'INDEX_MEASUREMENT_UNITS';
export const INDEX_MEASUREMENT_UNITS_SUCCESS = 'INDEX_MEASUREMENT_UNITS_SUCCESS';
export const INDEX_MEASUREMENT_UNITS_FAIL = 'INDEX_MEASUREMENT_UNITS_FAIL';

export const CREATE_ONE_MEASUREMENT_UNIT = 'CREATE_ONE_MEASUREMENT_UNIT';
export const CREATE_ONE_MEASUREMENT_UNIT_SUCCESS = 'CREATE_ONE_MEASUREMENT_UNIT_SUCCESS';
export const CREATE_ONE_MEASUREMENT_UNIT_FAIL = 'CREATE_ONE_MEASUREMENT_UNIT_FAIL';

export const UPDATE_ONE_MEASUREMENT_UNIT = 'UPDATE_ONE_MEASUREMENT_UNIT';
export const UPDATE_ONE_MEASUREMENT_UNIT_SUCCESS = 'UPDATE_ONE_MEASUREMENT_UNIT_SUCCESS';
export const UPDATE_ONE_MEASUREMENT_UNIT_FAIL = 'UPDATE_ONE_MEASUREMENT_UNIT_FAIL';

export const DELETE_ONE_MEASUREMENT_UNIT = 'DELETE_ONE_MEASUREMENT_UNIT';
export const DELETE_ONE_MEASUREMENT_UNIT_SUCCESS = 'DELETE_ONE_MEASUREMENT_UNIT_SUCCESS';
export const DELETE_ONE_MEASUREMENT_UNIT_FAIL = 'DELETE_ONE_MEASUREMENT_UNIT_FAIL';

export const INDEX_FEATURES = 'INDEX_FEATURES';
export const INDEX_FEATURES_SUCCESS = 'INDEX_FEATURES_SUCCESS';
export const INDEX_FEATURES_FAIL = 'INDEX_FEATURES_FAIL';

export const CREATE_ONE_FEATURE = 'CREATE_ONE_FEATURE';
export const CREATE_ONE_FEATURE_SUCCESS = 'CREATE_ONE_FEATURE_SUCCESS';
export const CREATE_ONE_FEATURE_FAIL = 'CREATE_ONE_FEATURE_FAIL';

export const UPDATE_ONE_FEATURE = 'UPDATE_ONE_FEATURE';
export const UPDATE_ONE_FEATURE_SUCCESS = 'UPDATE_ONE_FEATURE_SUCCESS';
export const UPDATE_ONE_FEATURE_FAIL = 'UPDATE_ONE_FEATURE_FAIL';

export const DELETE_ONE_FEATURE = 'DELETE_ONE_FEATURE';
export const DELETE_ONE_FEATURE_SUCCESS = 'DELETE_ONE_FEATURE_SUCCESS';
export const DELETE_ONE_FEATURE_FAIL = 'DELETE_ONE_FEATURE_FAIL';

export const INDEX_SUBSCRIPTIONS = 'INDEX_SUBSCRIPTIONS';
export const INDEX_SUBSCRIPTIONS_SUCCESS = 'INDEX_SUBSCRIPTIONS_SUCCESS';
export const INDEX_SUBSCRIPTIONS_FAIL = 'INDEX_SUBSCRIPTIONS_FAIL';

export const CREATE_ONE_SUBSCRIPTION = 'CREATE_ONE_SUBSCRIPTION';
export const CREATE_ONE_SUBSCRIPTION_SUCCESS = 'CREATE_ONE_SUBSCRIPTION_SUCCESS';
export const CREATE_ONE_SUBSCRIPTION_FAIL = 'CREATE_ONE_SUBSCRIPTION_FAIL';

export const UPDATE_ONE_SUBSCRIPTION = 'UPDATE_ONE_SUBSCRIPTION';
export const UPDATE_ONE_SUBSCRIPTION_SUCCESS = 'UPDATE_ONE_SUBSCRIPTION_SUCCESS';
export const UPDATE_ONE_SUBSCRIPTION_FAIL = 'UPDATE_ONE_SUBSCRIPTION_FAIL';

export const DELETE_ONE_SUBSCRIPTION= 'DELETE_ONE_SUBSCRIPTION';
export const DELETE_ONE_SUBSCRIPTION_SUCCESS = 'DELETE_ONE_SUBSCRIPTION_SUCCESS';
export const DELETE_ONE_SUBSCRIPTION_FAIL = 'DELETE_ONE_SUBSCRIPTION_FAIL';

export const INDEX_ROLES = 'INDEX_ROLES';
export const INDEX_ROLES_SUCCESS = 'INDEX_ROLES_SUCCESS';
export const INDEX_ROLES_FAIL = 'INDEX_ROLES_FAIL';

export const CREATE_ONE_ROLE = 'CREATE_ONE_ROLE';
export const CREATE_ONE_ROLE_SUCCESS = 'CREATE_ONE_ROLE_SUCCESS';
export const CREATE_ONE_ROLE_FAIL = 'CREATE_ONE_ROLE_FAIL';


export const INDEX_PERMISSIONS = 'INDEX_PERMISSIONS';
export const INDEX_PERMISSIONS_SUCCESS = 'INDEX_PERMISSIONS_SUCCESS';
export const INDEX_PERMISSIONS_FAIL = 'INDEX_PERMISSIONS_FAIL';

export const CREATE_ONE_PERMISSION = 'CREATE_ONE_PERMISSION';
export const CREATE_ONE_PERMISSION_SUCCESS = 'CREATE_ONE_PERMISSION_SUCCESS';
export const CREATE_ONE_PERMISSION_FAIL = 'CREATE_ONE_PERMISSION_FAIL';

export const PREPARE_STATE = 'PREPARE_STATE';


export const ALERT = 'ALERT';

