export const INDEX_BRANDS = 'INDEX_BRANDS';
export const INDEX_BRANDS_SUCCESS = 'INDEX_BRANDS_SUCCESS';
export const INDEX_BRANDS_FAIL = 'INDEX_BRANDS_FAIL';

export const CREATE_ONE_BRAND = 'CREATE_ONE_BRAND';
export const CREATE_ONE_BRAND_SUCCESS = 'CREATE_ONE_BRAND_SUCCESS';
export const CREATE_ONE_BRAND_FAIL = 'CREATE_ONE_BRAND_FAIL';

export const UPDATE_ONE_BRAND = 'UPDATE_ONE_BRAND';
export const UPDATE_ONE_BRAND_SUCCESS = 'UPDATE_ONE_BRAND_SUCCESS';
export const UPDATE_ONE_BRAND_FAIL = 'UPDATE_ONE_BRAND_FAIL';

export const DELETE_ONE_BRAND = 'DELETE_ONE_BRAND';
export const DELETE_ONE_BRAND_SUCCESS = 'DELETE_ONE_BRAND_SUCCESS';
export const DELETE_ONE_BRAND_FAIL = 'DELETE_ONE_BRAND_FAIL';


export const INDEX_MANUFACTURERS = 'INDEX_MANUFACTURERS';
export const INDEX_MANUFACTURERS_SUCCESS = 'INDEX_MANUFACTURERS_SUCCESS';
export const INDEX_MANUFACTURERS_FAIL = 'INDEX_MANUFACTURERS_FAIL';

export const CREATE_ONE_MANUFACTURER = 'CREATE_ONE_MANUFACTURER';
export const CREATE_ONE_MANUFACTURER_SUCCESS = 'CREATE_ONE_MANUFACTURER_SUCCESS';
export const CREATE_ONE_MANUFACTURER_FAIL = 'CREATE_ONE_MANUFACTURER_FAIL';

export const UPDATE_ONE_MANUFACTURER = 'UPDATE_ONE_MANUFACTURER';
export const UPDATE_ONE_MANUFACTURER_SUCCESS = 'UPDATE_ONE_MANUFACTURER_SUCCESS';
export const UPDATE_ONE_MANUFACTURER_FAIL = 'UPDATE_ONE_MANUFACTURER_FAIL';

export const DELETE_ONE_MANUFACTURER = 'DELETE_ONE_MANUFACTURER';
export const DELETE_ONE_MANUFACTURER_SUCCESS = 'DELETE_ONE_MANUFACTURER_SUCCESS';
export const DELETE_ONE_MANUFACTURER_FAIL = 'DELETE_ONE_MANUFACTURER_FAIL';



export const INDEX_COMPANIES = 'INDEX_COMPANIES';
export const INDEX_COMPANIES_SUCCESS = 'INDEX_COMPANIES_SUCCESS';
export const INDEX_COMPANIES_FAIL = 'INDEX_COMPANIES_FAIL';

export const CREATE_ONE_COMPANY = 'CREATE_ONE_COMPANY';
export const CREATE_ONE_COMPANY_SUCCESS = 'CREATE_ONE_COMPANY_SUCCESS';
export const CREATE_ONE_COMPANY_FAIL = 'CREATE_ONE_COMPANY_FAIL';

export const UPDATE_ONE_COMPANY = 'UPDATE_ONE_COMPANY';
export const UPDATE_ONE_COMPANY_SUCCESS = 'UPDATE_ONE_COMPANY_SUCCESS';
export const UPDATE_ONE_COMPANY_FAIL = 'UPDATE_ONE_COMPANY_FAIL';

export const DELETE_ONE_COMPANY = 'DELETE_ONE_COMPANY';
export const DELETE_ONE_COMPANY_SUCCESS = 'DELETE_ONE_COMPANY_SUCCESS';
export const DELETE_ONE_COMPANY_FAIL = 'DELETE_ONE_COMPANY_FAIL';

export const INDEX_USERS = 'INDEX_USERS';
export const INDEX_USERS_SUCCESS = 'INDEX_USERS_SUCCESS';
export const INDEX_USERS_FAIL = 'INDEX_USERS_FAIL';

export const CREATE_ONE_USER = 'CREATE_ONE_USER';
export const CREATE_ONE_USER_SUCCESS = 'CREATE_ONE_USER_SUCCESS';
export const CREATE_ONE_USER_FAIL = 'CREATE_ONE_USER_FAIL';

export const UPDATE_ONE_USER = 'UPDATE_ONE_USER';
export const UPDATE_ONE_USER_SUCCESS = 'UPDATE_ONE_USER_SUCCESS';
export const UPDATE_ONE_USER_FAIL = 'UPDATE_ONE_USER_FAIL';

export const DELETE_ONE_USER = 'DELETE_ONE_USER';
export const DELETE_ONE_USER_SUCCESS = 'DELETE_ONE_USER_SUCCESS';
export const DELETE_ONE_USER_FAIL = 'DELETE_ONE_USER_FAIL';

export const INDEX_BRANCHES = 'INDEX_BRANCHES';
export const INDEX_BRANCHES_SUCCESS = 'INDEX_BRANCHES_SUCCESS';
export const INDEX_BRANCHES_FAIL = 'INDEX_BRANCHES_FAIL';

export const CREATE_ONE_BRANCH = 'CREATE_ONE_BRANCH';
export const CREATE_ONE_BRANCH_SUCCESS = 'CREATE_ONE_BRANCH_SUCCESS';
export const CREATE_ONE_BRANCH_FAIL = 'CREATE_ONE_BRANCH_FAIL';

export const UPDATE_ONE_BRANCH = 'UPDATE_ONE_BRANCH';
export const UPDATE_ONE_BRANCH_SUCCESS = 'UPDATE_ONE_BRANCH_SUCCESS';
export const UPDATE_ONE_BRANCH_FAIL = 'UPDATE_ONE_BRANCH_FAIL';

export const DELETE_ONE_BRANCH = 'DELETE_ONE_BRANCH';
export const DELETE_ONE_BRANCH_SUCCESS = 'DELETE_ONE_BRANCH_SUCCESS';
export const DELETE_ONE_BRANCH_FAIL = 'DELETE_ONE_BRANCH_FAIL';

export const INDEX_BUSINESS_CATEGORIES = 'INDEX_BUSINESS_CATEGORIES';
export const INDEX_BUSINESS_CATEGORIES_SUCCESS = 'INDEX_BUSINESS_CATEGORIES_SUCCESS';
export const INDEX_BUSINESS_CATEGORIES_FAIL = 'INDEX_BUSINESS_CATEGORIES_FAIL';

export const CREATE_ONE_BUSINESS_CATEGORY = 'CREATE_ONE_BUSINESS_CATEGORY';
export const CREATE_ONE_BUSINESS_CATEGORY_SUCCESS = 'CREATE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const CREATE_ONE_BUSINESS_CATEGORY_FAIL = 'CREATE_ONE_BUSINESS_CATEGORY_FAIL';

export const UPDATE_ONE_BUSINESS_CATEGORY = 'UPDATE_ONE_BUSINESS_CATEGORY';
export const UPDATE_ONE_BUSINESS_CATEGORY_SUCCESS = 'UPDATE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const UPDATE_ONE_BUSINESS_CATEGORY_FAIL = 'UPDATE_ONE_BUSINESS_CATEGORY_FAIL';

export const DELETE_ONE_BUSINESS_CATEGORY = 'DELETE_ONE_BUSINESS_CATEGORY';
export const DELETE_ONE_BUSINESS_CATEGORY_SUCCESS = 'DELETE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const DELETE_ONE_BUSINESS_CATEGORY_FAIL = 'DELETE_ONE_BUSINESS_CATEGORY_FAIL';

export const INDEX_PRODUCT_CATEGORIES = 'INDEX_PRODUCT_CATEGORIES';
export const INDEX_PRODUCT_CATEGORIES_SUCCESS = 'INDEX_PRODUCT_CATEGORIES_SUCCESS';
export const INDEX_PRODUCT_CATEGORIES_FAIL = 'INDEX_PRODUCT_CATEGORIES_FAIL';

export const CREATE_ONE_PRODUCT_CATEGORY = 'CREATE_ONE_PRODUCT_CATEGORY';
export const CREATE_ONE_PRODUCT_CATEGORY_SUCCESS = 'CREATE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const CREATE_ONE_PRODUCT_CATEGORY_FAIL = 'CREATE_ONE_PRODUCT_CATEGORY_FAIL';

export const UPDATE_ONE_PRODUCT_CATEGORY = 'UPDATE_ONE_PRODUCT_CATEGORY';
export const UPDATE_ONE_PRODUCT_CATEGORY_SUCCESS = 'UPDATE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_ONE_PRODUCT_CATEGORY_FAIL = 'UPDATE_ONE_PRODUCT_CATEGORY_FAIL';

export const DELETE_ONE_PRODUCT_CATEGORY = 'DELETE_ONE_PRODUCT_CATEGORY';
export const DELETE_ONE_PRODUCT_CATEGORY_SUCCESS = 'DELETE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_ONE_PRODUCT_CATEGORY_FAIL = 'DELETE_ONE_PRODUCT_CATEGORY_FAIL';

export const INDEX_PRODUCTS = 'INDEX_PRODUCTS';
export const INDEX_PRODUCTS_SUCCESS = 'INDEX_PRODUCTS_SUCCESS';
export const INDEX_PRODUCTS_FAIL = 'INDEX_PRODUCTS_FAIL';

export const CREATE_ONE_PRODUCT = 'CREATE_ONE_PRODUCT';
export const CREATE_ONE_PRODUCT_SUCCESS = 'CREATE_ONE_PRODUCT_SUCCESS';
export const CREATE_ONE_PRODUCT_FAIL = 'CREATE_ONE_PRODUCT_FAIL';

export const UPDATE_ONE_PRODUCT = 'UPDATE_ONE_PRODUCT';
export const UPDATE_ONE_PRODUCT_SUCCESS = 'UPDATE_ONE_PRODUCT_SUCCESS';
export const UPDATE_ONE_PRODUCT_FAIL = 'UPDATE_ONE_PRODUCT_FAIL';

export const DELETE_ONE_PRODUCT = 'DELETE_ONE_PRODUCT';
export const DELETE_ONE_PRODUCT_SUCCESS = 'DELETE_ONE_PRODUCT_SUCCESS';
export const DELETE_ONE_PRODUCT_FAIL = 'DELETE_ONE_PRODUCT_FAIL';

export const PREPARE_STATE = 'PREPARE_STATE';


export const ALERT = 'ALERT';



/*
brands: [],
  companies: [],
  branches: [],
  products: [],
  manufacturers: [],
  product_categories: [],
  business_categories: [],
  users: [],
  clients: [],
 */
