export default {
  brands: [],
  companies: [],
  branches: [],
  products: [],
  manufacturers: [],
  product_categories: [],
  business_categories: [],
  product_segments: [],
  product_segment_entries: [],
  users: [],
  clients: [],
  customers: [],
  measurement_units: [],
  features: [],
  subscriptions: [],
  roles: [],
  permissions: [],
  cools: [],
  showing: {}
};
