export default {
    login: "/login",
    products: "/products",
    brands: "/brands",
    product_categories : "/product_categories",
    manufacturers : "/manufacturers",
    branch_details : "/users/:id/companies/:id/branches/:id/details",
    branches : "/users/:id/companies/:id/branches",
    companies : "/users/:id/companies",
    business_categories : "/business_categories",
    users: "/users",
    product_segments: "/product_segments",
    product_segment_entries: "/product_segments/:id/product_segment_entries",
    customers: "/customers",
    measurement_units: "/measurement_unit",
    features: "/features",
    subscriptions: "/subscription",
    roles: "/roles",
    permissions: "/permissions",
    cools: "/cools"
};
